name: Build, Test, Lint, and Deploy Frontend Web App

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup_build_test_lint_deploy:
    name: Setup, Build, Run Tests, Lint, and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Use the specified Yarn version
        run: corepack prepare yarn@4.4.0 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        env:
          NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
        run: yarn build

      - name: Run lint
        run: yarn lint
